[package]
name = "bin"
edition = "2024"

[[bin]]
path = "main.rs"
name = "cheesecake-app"

[dependencies]
dotenvy = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
config = { path = "../config" }
axum = { workspace = true }
controllers = { path = "../app/controllers" }
