[package]
name = "bin"
version = "0.1.0"
edition = "2024"

[[bin]]
path = "main.rs"
name = "cheesecake-app"

[dependencies]
dotenvy = "0.15.7"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1.41"
config = { path = "../config" }
axum = { version = "0.8.3", features = ["tokio"] }
controllers = { path = "../app/controllers" }
